name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Terraform CI/CD"]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: romman1998/gymprogress
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy Docker container on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 52.90.168.25         # Public IP or DNS of your EC2
          username: ec2-user                     # Default user for Amazon Linux
          key: ${{ secrets.SSH_PRIVATE_KEY }}       # Your private key as GitHub secret
          port: 22
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull $IMAGE_NAME:$IMAGE_TAG
            /home/ec2-user/deploy.sh

