name: Deploy to EC2

on:
  push:
    branches:
      - master  # Trigger on master push

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: romman1998/gymprogress
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy Docker container on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 54.146.46.33          # Public IP or DNS of your EC2
          username: ec2-user                     # Default user for Amazon Linux
          key: ${{ secrets.SSH_PRIVATE_KEY }}       # Your private key as GitHub secret
          port: 22
          script: |
            docker pull ${{secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
            docker stop gymprogress || true
            docker rm -f gymprogress || true
            docker run -d --name gymprogress -p 80:80 ${{secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
