name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      # These are your GitHub secrets
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform -chdir=Terraform init

      - name: Terraform Validate
        run: terraform validate Terraform

      - name: Terraform Plan
        run: terraform -chdir=Terraform plan -out=tfplan

      # Optional: auto-apply only on master
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform -chdir=Terraform apply -auto-approve tfplan
